In [2]:
import numpy as np
arr1 = np.array([
    [1,2,3], [4,5,6], [7,8,9]
])
print("Original array:",arr1)
result = np.transpose(arr1)
print("transpose array:")
print(result)

Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
# Transpose of a 2D matrix
def transpose(matrix):
    # Using list comprehension to swap rows and columns
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

# Example matrix
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Transposing and printing the matrix
transposed_matrix = transpose(matrix)
print(transposed_matrix)


[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
