In [2]:
import numpy as np
arr1 = np.array([
    [1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([
    [10,20,30], [40,50,60], [70,80,90]])
result = arr1 + arr2
print(result)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [4]:
import numpy as np
arr1 = np.array([
    [1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([
    [10,20,30], [40,50,60], [70,80,90]])

result = []
for i in range(len(arr1)):
    row = []
    for j in range(len(arr1[0])):
        row.append(arr1[i,j]+arr2[i,j])
    result.append(row)
print(result)

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]
