In [2]:
import numpy as np
x = np.array([3,5,2,7,8,4,5])
type(x)
print(x[::-1]) #slicing method

[5 4 8 7 2 5 3]


In [4]:
import numpy as np
x = np.array([3,5,2,7,8,4,5,])
n = len(x)
for i in range (n-1,-1,-1):
    print(x[i])

5
4
8
7
2
5
3


In [6]:
import numpy as np
x = np.array([3,5,2,7,8,4,5,])
n=len(x)
new_arr=[]
for i in range(n-1,-1,-1):
    new_arr.append(x[i])
print(new_arr)


[5, 4, 8, 7, 2, 5, 3]


In [51]:
import numpy as np

def remove_duplicates(x):
    new_arr=[]
    for i in x:
        if i not in new_arr:
            new_arr.append(i)
    return new_arr
print(type(x))
print(x)
remove_duplicates(np.array([3,5,2,7,8,4,5,]))


<class 'numpy.ndarray'>
[3 3 4 5 6 7 7 7]


[3, 5, 2, 7, 8, 4]

In [24]:
import numpy as np
def rd(x):
    na=[]
    for i in x:
        if i not in na:
            na.append(i)
    return na
rd(np.array([3,3,4,5,6,7,7,7])) #if we not specify np.array means it is list

[3, 4, 5, 6, 7]

In [47]:
import numpy as np

def remove_duplicates(x):
    unique_element = list(set(x))
    return np.array(unique_element)
(np.array([3,3,4,5,6,7,7,7]))

array([3, 3, 4, 5, 6, 7, 7, 7])

In [49]:
import numpy as np

def remove_duplicates(x):
    unique_element = list(set(x))  # Convert array to set to remove duplicates, then back to list
    return np.array(unique_element)  # Convert back to NumPy array

x = np.array([3, 3, 4, 5, 6, 7, 7, 7])  # Define NumPy array
result = remove_duplicates(x)  # Call function to remove duplicates

print(result)  # Print the output


[3 4 5 6 7]


In [58]:
import numpy as np

def find_index(arr, element):
    try:
        unique_arr = np.unique(arr)  # Removes duplicates while preserving order
        return np.where(unique_arr == element)[0][0]  # Finds index of element
    except IndexError:
        return "Element not found"

# Example usage
x = np.array([3, 3, 4, 5, 6, 7, 7, 7])
print(find_index(x, 5))  # Output: 2
print(find_index(x, 2))  # Output: Element not found


2
Element not found


In [53]:
def find_index(lst, element):
    try:
        return lst.index(element)  # Find index of element
    except ValueError:
        return "Element not found"

# Example usage
numbers = [3, 5, 7, 9, 11]
print(find_index(numbers, 7))  # Output: 2
print(find_index(numbers, 4))  # Output: Element not found


2
Element not found


In [60]:
def find_index(arr, element):
    try:
        return arr.index(element)  # Find the index of the element
    except ValueError:  # Handles case when element is not found
        return -1

# Example usage
numbers = [3, 5, 7, 9, 11]
print(find_index(numbers, 7))  # Output: 2
print(find_index(numbers, 4))  # Output: -1


2
-1
